type FootBallMatchStatistic = {
  'Match ID': string;
  'P1 Accurate passes': string;
  'P1 Aerials won': string;
  'P1 Ball possession': string;
  'P1 Big chances': string;
  'P1 Big chances missed': string;
  'P1 Blocked shots': string;
  'P1 Clearances': string;
  'P1 Corner kicks': string;
  'P1 Crosses': string;
  'P1 Dribbles': string;
  'P1 Duels won': string;
  'P1 Expected goals': string;
  'P1 Fouls': string;
  'P1 Free kicks': string;
  'P1 Goal kicks': string;
  'P1 Goalkeeper saves': string;
  'P1 Goals prevented': string;
  'P1 Interceptions': string;
  'P1 Long balls': string;
  'P1 Offsides': string;
  'P1 Passes': string;
  'P1 Possession lost': string;
  'P1 Red cards': string;
  'P1 Shots inside box': string;
  'P1 Shots off target': string;
  'P1 Shots on target': string;
  'P1 Shots outside box': string;
  'P1 Tackles': string;
  'P1 Throw-ins': string;
  'P1 Total shots': string;
  'P1 Yellow cards': string;
  'P1 name': string;

  'P2 Accurate passes': string;
  'P2 Aerials won': string;
  'P2 Ball possession': string;
  'P2 Big chances': string;
  'P2 Big chances missed': string;
  'P2 Blocked shots': string;
  'P2 Clearances': string;
  'P2 Corner kicks': string;
  'P2 Crosses': string;
  'P2 Dribbles': string;
  'P2 Duels won': string;
  'P2 Expected goals': string;
  'P2 Fouls': string;
  'P2 Free kicks': string;
  'P2 Goal kicks': string;
  'P2 Goalkeeper saves': string;
  'P2 Goals prevented': string;
  'P2 Interceptions': string;
  'P2 Long balls': string;
  'P2 Offsides': string;
  'P2 Passes': string;
  'P2 Possession lost': string;
  'P2 Red cards': string;
  'P2 Shots inside box': string;
  'P2 Shots off target': string;
  'P2 Shots on target': string;
  'P2 Shots outside box': string;
  'P2 Tackles': string;
  'P2 Throw-ins': string;
  'P2 Total shots': string;
  'P2 Yellow cards': string;
  'P2 name': string;
};
